### ISSUE TITLE
Adding possibility to create an alloy requesting absolutly a special tier of machine...

### ISSUE THREAD

**Issue by Fireztonez** [Shadows-of-Fire/EnderTweaker#7] opened 2019-03-08 06:55 UTC
Hello,
I don't know if this is possibly with teh EnderIO API now, but, if this is possible, can you add possibility to make a recipes for an enhanced machine and not for the basic tier...

I know the basic tier of alloy smelter can'T be used like a furnace, and there have an icon to say you need an upgraded machine to do that craft, so possibly you can make an alloy for un eupgraded machine only...?

Thank's

**Comment by Shadows-of-Fire** [comment] 2019-03-08 07:05
Duplicate of #4
(Their API supports it, but it's not really implemented on their end)

**Closed as completed by Shadows-of-Fire** 2019-03-08 07:05 UTC
Labels: duplicate

**Comment by Fireztonez** [comment] 2019-03-08 07:43
ok, sorry I miss the other message about that...

And thank's for the information...
So I have to make request to EnderIO for that...
